# IPython log file

get_ipython().magic(u'logstart Oct28.py')
import random
random.uniform(-1,1)
random.uniform(-1,1)
random.uniform(-1,1)
random.uniform(-1,1)
random.uniform(-1,1)
n = 10000
r = [random.uniform(-1,1) for i in range(n)]
from scitools.std import *
plot(r, '+')
n = 500
r = [random.uniform(-1,1) for i in range(n)]
plot(r, '+')
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
plot(r, '+')
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
plot(r, '+')
plot(r, '+')
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,6)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
random.randint(1,7)
r = [random.randint(1,7) for i in range(n)]
plot(r, '+')
import numpy
import numpy as np
np.random.uniform(-1,1,5000)
np.random.uniform(-1,1,5000)
np.random.randint(1,7,size=20)
np.random.randint(1,7,20)
np.random.randint(1,7,50000)
